Py3 porting
cloudify-cosmo/cloudify-managed-nagios-plugin pull request #9
Opened 2021-01-14 08:27 UTC by jrzeszutek

* tested on 5.1 with centos core py3 agent using example blueprint

2021-01-26 17:47 UTC, EarthmanT requested changes

2021-01-26 17:47 UTC, EarthmanT commented on integration_tests/test_base.py
> +from __future__ import absolute_import
No need for this `from __future__ import absolute_import`

2021-01-26 17:47 UTC, EarthmanT commented on integration_tests/test_server.py
> +from cloudify._compat import text_type
This will only work on a `5.1` manager. best to create a local compat until 5.0.5 is no longer supported.

2021-01-26 17:47 UTC, EarthmanT commented on integration_tests/utils.py
> +from __future__ import print_function
No need to import. `from __future__ import print_function`

2021-01-26 17:47 UTC, EarthmanT commented on managed_nagios_plugin/resources/scripts/logging_utils.py
> +from builtins import object
No need to import `from builtins import object`

2021-01-26 17:47 UTC, EarthmanT commented on managed_nagios_plugin/snmp_utils.py
> +from cloudify._compat import text_type
No need to import:
```
from builtins import zip
from builtins import object
```

2021-01-26 17:47 UTC, EarthmanT commented on managed_nagios_plugin/target_type/tasks.py
> +from cloudify._compat import text_type
Make a _compat for just this plugin instead of importing 5.1 compat.

2021-02-24 15:06 UTC, kfrukacz-gs commented
@EarthmanT any open issues? Can we marge and release?

2021-03-01 09:12 UTC, merged